/**
 * Native host installation (Phase 14): host manifest, launcher, host config
 * and per-user browser registration; uninstall removes all of it.
 *
 * Windows (per user, no admin rights):
 *   HKCU\Software\Google\Chrome\NativeMessagingHosts\<name>     (default) = <manifest>
 *   HKCU\Software\Microsoft\Edge\NativeMessagingHosts\<name>
 *   HKCU\Software\Chromium\NativeMessagingHosts\<name>
 * Linux / macOS: <browser config dir>/NativeMessagingHosts/<name>.json, and
 * `<user-data-dir>/NativeMessagingHosts/` for custom profiles.
 *
 * `planInstall` / `planUninstall` are pure (unit-tested for every platform);
 * `applyInstall` / `applyUninstall` perform the plan through injected effects.
 * Re-running install is an upgrade (files rewritten, keys overwritten);
 * uninstalling something absent is not an error.
 */

import { execFileSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, rmdirSync, writeFileSync } from "node:fs";
import { dirname, posix, win32 } from "node:path";

import { EXTENSION_ID_RE, NATIVE_HOST_NAME, isLoopbackUrl } from "../shared.ts";
import { validateNativeHostConfig } from "./config.ts";

export type BrowserKind = "chrome" | "edge" | "chromium";
export const BROWSERS: readonly BrowserKind[] = ["chrome", "edge", "chromium"];

const REGISTRY_ROOT: Record<BrowserKind, string> = {
  chrome: "HKCU\\Software\\Google\\Chrome\\NativeMessagingHosts",
  edge: "HKCU\\Software\\Microsoft\\Edge\\NativeMessagingHosts",
  chromium: "HKCU\\Software\\Chromium\\NativeMessagingHosts",
};
const LINUX_DIR: Record<BrowserKind, string> = { chrome: ".config/google-chrome", edge: ".config/microsoft-edge", chromium: ".config/chromium" };
const MAC_DIR: Record<BrowserKind, string> = {
  chrome: "Library/Application Support/Google/Chrome",
  edge: "Library/Application Support/Microsoft Edge",
  chromium: "Library/Application Support/Chromium",
};

export const MANIFEST_FILE = `${NATIVE_HOST_NAME}.json`;
export const CONFIG_FILE = "native-host.json";
export const LAUNCHER_WIN = "lab-native-host.cmd";
export const LAUNCHER_POSIX = "lab-native-host.sh";

export class InstallError extends Error {}

export interface InstallTarget {
  platform: NodeJS.Platform;
  installDir: string;
  browsers?: readonly BrowserKind[];
  /** POSIX home directory (manifest locations). */
  home?: string;
  /** Extra profiles: `<dir>/NativeMessagingHosts/` (POSIX only; Windows uses the registry). */
  userDataDirs?: readonly string[];
}

export interface InstallOptions extends InstallTarget {
  extensionIds: readonly string[];
  serviceUrl: string;
  nodePath: string;
  /** Absolute path of windows-service/src/native/main.ts. */
  hostEntry: string;
  logDir: string;
  timeoutMs?: number;
}

export interface PlannedFile {
  path: string;
  content: string;
  mode: number;
}

export interface InstallPlan {
  platform: NodeJS.Platform;
  manifestPath: string;
  launcherPath: string;
  configPath: string;
  files: PlannedFile[];
  /** Windows: registry keys whose default value is the manifest path. */
  registry: Array<{ key: string; value: string }>;
  manifest: Record<string, unknown>;
}

export interface UninstallPlan {
  platform: NodeJS.Platform;
  files: string[];
  registryKeys: string[];
  /** Removed when empty afterwards. */
  dirs: string[];
}

function pathApi(platform: NodeJS.Platform): typeof posix {
  return platform === "win32" ? win32 : posix;
}

function manifestLocations(t: InstallTarget): string[] {
  const p = pathApi(t.platform);
  const out: string[] = [];
  if (t.platform !== "win32") {
    const table = t.platform === "darwin" ? MAC_DIR : LINUX_DIR;
    if (t.home) for (const b of t.browsers ?? BROWSERS) out.push(p.join(t.home, table[b], "NativeMessagingHosts", MANIFEST_FILE));
    for (const d of t.userDataDirs ?? []) out.push(p.join(d, "NativeMessagingHosts", MANIFEST_FILE));
  }
  return out;
}

function registryKeys(t: InstallTarget): string[] {
  return t.platform === "win32" ? (t.browsers ?? BROWSERS).map((b) => `${REGISTRY_ROOT[b]}\\${NATIVE_HOST_NAME}`) : [];
}

/** cmd.exe expands these even inside quotes; such paths are refused rather than escaped. */
const CMD_UNSAFE = /["%^&|<>!\r\n]/;

function shQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

export function launcherContent(platform: NodeJS.Platform, nodePath: string, hostEntry: string, configPath: string): string {
  if (platform === "win32") {
    for (const v of [nodePath, hostEntry, configPath]) if (CMD_UNSAFE.test(v)) throw new InstallError(`path not usable in a .cmd launcher: ${v}`);
    return [
      "@echo off",
      "rem Automation Lab native messaging host launcher (generated by the installer; do not edit).",
      `"${nodePath}" --experimental-strip-types --no-warnings "${hostEntry}" --config "${configPath}" %*`,
      "",
    ].join("\r\n");
  }
  return [
    "#!/bin/sh",
    "# Automation Lab native messaging host launcher (generated by the installer; do not edit).",
    `exec ${shQuote(nodePath)} --experimental-strip-types --no-warnings ${shQuote(hostEntry)} --config ${shQuote(configPath)} "$@"`,
    "",
  ].join("\n");
}

export function planInstall(o: InstallOptions): InstallPlan {
  const p = pathApi(o.platform);
  if (!p.isAbsolute(o.installDir) || !p.isAbsolute(o.nodePath) || !p.isAbsolute(o.hostEntry) || !p.isAbsolute(o.logDir)) {
    throw new InstallError("installDir, nodePath, hostEntry and logDir must be absolute paths");
  }
  if (o.extensionIds.length === 0) throw new InstallError("at least one --extension-id is required (see chrome://extensions)");
  for (const id of o.extensionIds) if (!EXTENSION_ID_RE.test(id)) throw new InstallError(`not a Chrome extension id: ${id}`);
  if (!isLoopbackUrl(o.serviceUrl)) throw new InstallError(`service URL must be loopback: ${o.serviceUrl}`);
  for (const b of o.browsers ?? BROWSERS) if (!BROWSERS.includes(b)) throw new InstallError(`unknown browser: ${String(b)}`);

  const manifestPath = p.join(o.installDir, MANIFEST_FILE);
  const configPath = p.join(o.installDir, CONFIG_FILE);
  const launcherPath = p.join(o.installDir, o.platform === "win32" ? LAUNCHER_WIN : LAUNCHER_POSIX);
  const allowedOrigins = [...new Set(o.extensionIds)].map((id) => `chrome-extension://${id}/`);

  const config = { serviceUrl: o.serviceUrl.replace(/\/+$/, ""), allowedOrigins, timeoutMs: o.timeoutMs ?? 10_000, logDir: o.logDir };
  const v = validateNativeHostConfig(config);
  if (!v.ok) throw new InstallError(`invalid host config: ${v.errors.join("; ")}`);

  const manifest = {
    name: NATIVE_HOST_NAME,
    description: "Automation Lab bridge: relays the recorder extension to the local lab service (loopback).",
    path: launcherPath,
    type: "stdio",
    allowed_origins: allowedOrigins,
  };
  const manifestJson = `${JSON.stringify(manifest, null, 2)}\n`;
  const files: PlannedFile[] = [
    { path: configPath, content: `${JSON.stringify(config, null, 2)}\n`, mode: 0o600 },
    { path: launcherPath, content: launcherContent(o.platform, o.nodePath, o.hostEntry, configPath), mode: 0o700 },
    { path: manifestPath, content: manifestJson, mode: 0o644 },
    ...manifestLocations(o).map((path) => ({ path, content: manifestJson, mode: 0o644 })),
  ];
  return { platform: o.platform, manifestPath, launcherPath, configPath, files, registry: registryKeys(o).map((key) => ({ key, value: manifestPath })), manifest };
}

export function planUninstall(t: InstallTarget): UninstallPlan {
  const p = pathApi(t.platform);
  const own = [MANIFEST_FILE, CONFIG_FILE, t.platform === "win32" ? LAUNCHER_WIN : LAUNCHER_POSIX].map((f) => p.join(t.installDir, f));
  return { platform: t.platform, files: [...own, ...manifestLocations(t)], registryKeys: registryKeys(t), dirs: [t.installDir] };
}

// ---- effects ----

export interface InstallEffects {
  writeFile(path: string, content: string, mode: number): void;
  removeFile(path: string): boolean;
  removeDirIfEmpty(path: string): boolean;
  readFile(path: string): string | undefined;
  /** Returns the exit status (0 = success). */
  exec(cmd: string, args: readonly string[]): { status: number; stdout: string };
}

export const nodeEffects: InstallEffects = {
  writeFile(path, content, mode) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, { mode });
    try {
      chmodSync(path, mode);
    } catch {
      /* Windows ignores POSIX modes */
    }
  },
  removeFile(path) {
    if (!existsSync(path)) return false;
    rmSync(path, { force: true });
    return true;
  },
  removeDirIfEmpty(path) {
    try {
      if (!existsSync(path) || readdirSync(path).length > 0) return false;
      rmdirSync(path);
      return true;
    } catch {
      return false;
    }
  },
  readFile(path) {
    try {
      return readFileSync(path, "utf8");
    } catch {
      return undefined;
    }
  },
  exec(cmd, args) {
    try {
      const stdout = execFileSync(cmd, [...args], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"], windowsHide: true });
      return { status: 0, stdout };
    } catch (err) {
      const e = err as { status?: number; stdout?: string };
      return { status: typeof e.status === "number" ? e.status : 1, stdout: String(e.stdout ?? "") };
    }
  },
};

export function applyInstall(plan: InstallPlan, fx: InstallEffects = nodeEffects): { written: string[]; registry: string[] } {
  const written: string[] = [];
  for (const f of plan.files) {
    fx.writeFile(f.path, f.content, f.mode);
    written.push(f.path);
  }
  const registry: string[] = [];
  for (const r of plan.registry) {
    const res = fx.exec("reg", ["add", r.key, "/ve", "/t", "REG_SZ", "/d", r.value, "/f"]);
    if (res.status !== 0) throw new InstallError(`reg add failed for ${r.key} (exit ${res.status})`);
    registry.push(r.key);
  }
  return { written, registry };
}

export function applyUninstall(plan: UninstallPlan, fx: InstallEffects = nodeEffects): { removed: string[]; registryDeleted: string[]; absent: string[] } {
  const removed: string[] = [];
  const absent: string[] = [];
  for (const f of plan.files) (fx.removeFile(f) ? removed : absent).push(f);
  const registryDeleted: string[] = [];
  for (const key of plan.registryKeys) {
    if (fx.exec("reg", ["query", key, "/ve"]).status !== 0) {
      absent.push(key);
      continue;
    }
    const res = fx.exec("reg", ["delete", key, "/f"]);
    if (res.status !== 0) throw new InstallError(`reg delete failed for ${key} (exit ${res.status})`);
    registryDeleted.push(key);
  }
  for (const d of plan.dirs) fx.removeDirIfEmpty(d);
  return { removed, registryDeleted, absent };
}

export interface NativeHostStatus {
  installed: boolean;
  manifestPath: string;
  allowedOrigins: string[];
  registered: Array<{ where: string; ok: boolean }>;
  problems: string[];
}

/** Read back what is installed and whether it is consistent. */
export function nativeHostStatus(t: InstallTarget, fx: InstallEffects = nodeEffects): NativeHostStatus {
  const p = pathApi(t.platform);
  const manifestPath = p.join(t.installDir, MANIFEST_FILE);
  const problems: string[] = [];
  let allowedOrigins: string[] = [];
  let launcher: string | undefined;
  const raw = fx.readFile(manifestPath);
  if (raw === undefined) problems.push(`no host manifest at ${manifestPath}`);
  else {
    try {
      const m = JSON.parse(raw) as { name?: unknown; path?: unknown; allowed_origins?: unknown };
      if (m.name !== NATIVE_HOST_NAME) problems.push("manifest name mismatch");
      launcher = typeof m.path === "string" ? m.path : undefined;
      allowedOrigins = Array.isArray(m.allowed_origins) ? m.allowed_origins.filter((x): x is string => typeof x === "string") : [];
      if (!launcher || fx.readFile(launcher) === undefined) problems.push(`launcher missing: ${String(m.path)}`);
    } catch {
      problems.push("manifest is not valid JSON");
    }
  }
  const cfgRaw = fx.readFile(p.join(t.installDir, CONFIG_FILE));
  if (cfgRaw === undefined) problems.push("host config missing");
  else {
    try {
      const v = validateNativeHostConfig(JSON.parse(cfgRaw));
      if (!v.ok) problems.push(`host config invalid: ${v.errors.join("; ")}`);
    } catch {
      problems.push("host config is not valid JSON");
    }
  }
  const registered: NativeHostStatus["registered"] = [];
  for (const key of registryKeys(t)) {
    const q = fx.exec("reg", ["query", key, "/ve"]);
    registered.push({ where: key, ok: q.status === 0 && q.stdout.includes(manifestPath) });
  }
  for (const loc of manifestLocations(t)) registered.push({ where: loc, ok: fx.readFile(loc) !== undefined });
  if (registered.length > 0 && !registered.some((r) => r.ok)) problems.push("not registered with any browser");
  return { installed: problems.length === 0, manifestPath, allowedOrigins, registered, problems };
}

